defaults:
  - agent: dqn
  - road_network: cologne1

trainer:
  episodes: 200
  batch_size: 128
  learning_rate: 0.01

environment:
  use_gui: False
  delta_time: 10
  yellow_time: 4
  min_green: 10
  sumo_seed: 0
  observation: image_like_vehicle_info # possible values: lane_vehicle_count, lane_waiting_time, and image_like_vehicle_info
  reward_fn: pressure # possible values: pressure, queue_length, and diff_queue_length

experiment:
  name: trial
  seed: 1
  torch_deterministic: True
  train: True
  runs: 5
  should_log: True
  load_dir: ""
