name: ppo
actor_learning_rate: 0.1
critic_learning_rate: 0.1
gamma: 0.99
gae_lambda: 0.95
update_epochs: 1
norm_adv: True
clip_coef: 0.1
clip_vloss: True
ent_coef: 0.1
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
batch_size: 360